# -*- coding: utf-8 -*-
"""GoProtect_streamlit.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QuW-pnOpBNUzMvqF1PSV4-clCQ6WfUHM
"""

import streamlit as st

st.title('Поиск наиболее подходящих элементов для фигуриста')
st.caption('Поиск наиболее подходящих элементов для фигуриста')